name: ehr-big-data
dependencies:
- python=3.5.1
- pip:
  - pandas==0.19.2
  - pytesseract==0.2.5
  - scipy==1.1.0
  - tensorflow==1.10.0
  - Pillow==5.3.0
  - pymongo[tls,srv]==3.7.2
  - Wand==0.4.5
  - reportlab==3.5.12
  - canvas==0.2
  - imutils==0.3.6
  - opencv-python==3.4.4.19
